### ISSUE TITLE
Add Photon in python section

### ISSUE THREAD

**Issue by s0md3v** [BruceDone/awesome-crawler#37]
Photon is an incredibly fast crawler which extracts URLs, website accounts, emails, files, endpoints and much more.

[https://github.com/s0md3v/Photon](https://github.com/s0md3v/Photon)

**Comment by BruceDone** [comment]
Thanks for your request , but your project does not have so much feature , or new things compare to other project on the list , even you have so much starts , but means not so much for me . :)

**Comment by Souhardya** [comment]
Is this LOSS

**Comment by Biprodeep** [comment]
Someone said it finally ;)

**Comment by s0md3v** [comment]
Ye behan ka lund idhar b aa gya gaand mraane xD
