### ISSUE TITLE
Add Mercator URL Frontier implementation

### ISSUE THREAD

**Issue by moredure** [BruceDone/awesome-crawler#61]
@BruceDone checkout https://github.com/BruceDone/awesome-crawler/pull/62  please, added reference to https://dev.to/spacenomad/mercator-url-frontier-in-golang-15o2

**Comment by BruceDone** [comment]
Is this a framework ?  @moredure

**Comment by moredure** [comment]
Hello @BruceDone, I have some ideas to wrap it into a framework, but generally it is just a reference implementation of Mercator Crawler URL Frontier in Golang, which allows to conduct smart (calculate windows between requests to the same host) and polite crawling as well as to enable crawling without memory limitations for URL queues both seed and collected during crawling.

**Comment by moredure** [comment]
Should it be a complete framework to pass your moderation @BruceDone , or just a useful reference will be enought?

**Comment by BruceDone** [comment]
Thanks for your contribute, but this repo just collect the crawler framework

**Comment by moredure** [comment]
Understood, thanks for your reply.
