### ISSUE TITLE
Fastest crawler or indexer in Rust [spider]

### ISSUE THREAD

**Issue by j-mendez** [BruceDone/awesome-crawler#88]
Rust based crawler or indexer https://github.com/spider-rs/spider. Also the fastest and most efficient OSS crawler.

**Comment by j-mendez** [comment]
A gRPC https://github.com/a11ywatch/crawler

**Comment by BruceDone** [comment]
@j-mendez you open a pull request,  i will merge it

**Comment by j-mendez** [comment]
> @j-mendez you can open a pull request, i will merge it

done 🙌 https://github.com/BruceDone/awesome-crawler/pull/89
